# Generated by Django 5.0.1 on 2024-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeimage',
            name='image',
            field=models.FileField(blank=True, upload_to='notices/'),
        ),
    ]
