# Generated by Django 5.0.1 on 2024-01-25 12:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_info_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.logoImageValidator
            ),
        ),
    ]
