# Generated by Django 5.0.1 on 2024-01-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_info_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='logo',
        ),
    ]
