# Generated by Django 5.0.1 on 2024-01-25 12:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_info_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="logo",
            field=models.ImageField(blank=True, upload_to="logo/"),
        ),
    ]
