# Generated by Django 5.0.1 on 2024-01-25 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_info_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="facebook",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="info",
            name="instagram",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="info",
            name="twitter",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
