# Generated by Django 5.0.1 on 2024-01-25 13:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_info_facebook_alter_info_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='logo',
            field=models.ImageField(blank=True, upload_to=app.models.logoImageValidator),
        ),
    ]
