# Generated by Django 5.0.1 on 2024-01-25 15:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_info_facebook_alter_info_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='about/')),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
