# Generated by Django 5.0.1 on 2024-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(choices=[('Principal', 'Principal'), ('BOD', 'BOD'), ('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], default='select', max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('facebook', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='OurTeam/')),
            ],
        ),
    ]
