# Generated by Django 5.0.1 on 2024-01-26 15:31

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='post',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Chairman', 'Chairman'), ('BOD', 'BOD'), ('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], default='select', max_length=25),
        ),
    ]
