# Generated by Django 5.0.1 on 2024-01-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('about', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.aboutus')),
            ],
        ),
    ]
