# Generated by Django 5.0.1 on 2024-01-28 14:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to=app.models.logoImageValidator),
        ),
    ]
