# Generated by Django 5.0.1 on 2024-02-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_gallery_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeimage',
            name='notice',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='NoticeImage',
        ),
    ]
