# Generated by Django 5.0.1 on 2024-02-18 13:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_noticeimage_notice_delete_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=app.models.logoImageValidator),
        ),
    ]
