# Generated by Django 5.0.1 on 2024-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_info_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
