# Generated by Django 5.0.1 on 2024-02-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_aboutus_meta_description_aboutus_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='meta_keywords',
        ),
    ]
