# Generated by Django 5.0.1 on 2024-02-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_gallery_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
    ]
