# Generated by Django 5.0.1 on 2024-02-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='event',
            new_name='blog',
        ),
    ]
